version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"  # Web management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # mysql:
  #   image: mysql:8.0.36
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: TigerRoot1234
  #     MYSQL_DATABASE: rtcdb
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - mysql_data:/var/lib/mysql
      
  # phpmyadmin:
  #   image: phpmyadmin:5.2.1
  #   links:
  #     - mysql
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: TigerRoot1234
  
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
  




volumes:
  rabbitmq_data:
  # mysql_data:
  # postgres_data: